name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天国际标准时间 0:00 自动触发
  workflow_dispatch: # 允许手动点击触发
  
permissions:
  contents: write
  workflows: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
            
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: main     # 你自己仓库需要同步的分支名
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动调用免密口令
          upstream_sync_branch: main   # 原作者上游仓库的分支名
          upstream_sync_repo: maillab/cloud-mail # 💡 记得修改成原作者的 "用户名/仓库名"
