name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天国际标准时间 0:00 自动触发
  workflow_dispatch: # 允许手动点击触发

# 💡 必须显式声明 contents 权限，否则 GITHUB_TOKEN 没有推送（push）权限
permissions:
  contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
            
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: main     
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} 
          upstream_sync_branch: main   
          upstream_sync_repo: maillab/cloud-mail 
