name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天国际标准时间 0:00 (北京时间早上 8:00) 自动触发
  workflow_dispatch: # 允许你在 Actions 页面手动点击按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-Action@v3.4
        with:
          target_sync_branch: main     # 你自己仓库需要同步的分支名
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动调用免密口令
          upstream_sync_branch: main   # 原作者上游仓库的分支名
          upstream_sync_repo: cloud-mail # 💡 记得修改成原作者的 "用户名/仓库名"
